### ISSUE TITLE
docker_entrypoint.sh : permission denied

### ISSUE THREAD

**Issue by monaung** [microservices-aspnetcore/hello-world#1]
I created hello-world, actually copy, from scratch
able to push to docker via wercker but after pull and run,  having following issue.

container_linux.go:265: starting container process caused "exec: \"/pipeline/source/app/docker_entrypoint.sh\": permission denied"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/pipeline/source/app/docker_entrypoint.sh\": permission denied".

**Comment by rafalpienkowski** [comment]
Add in your wercker.yml additional build step which will make file executable. An example of step below:

```
- script:
        name: chmod
        code: |
          chmod +x ./docker_entrypoint.sh
```
